### ISSUE TITLE
Question 11 may be missing a line

### ISSUE THREAD

**Issue by laarchambault** [learn-co-curriculum/ruby-oo-object-relationships-quiz#2]
Please double-check, but I believe one of the instance methods is incomplete. User#add_comment reads

```
def add_comment(text)
  comment.user = self
end
```

but I believe it should be 

```
def add_comment(text)
  comment = Comment.new(text)
  comment.user = self
end
```

**Comment by iambryanhaney** [comment]
Noticed as well.

**Comment by sylwiavargas** [comment]
Thank you, @laarchambault and @iambryanhaney, for drawing our attention to this. We've fixed it!
